export CUDA_VISIBLE_DEVICES=6,7

torchrun --nnodes=1 \
        --nproc_per_node=2 \
        --max_restarts=0 \
        --master_port=9050 \
        --rdzv_id=100 \
        --rdzv_backend="c10d" \
        ../../run.py \
                    --run_name="debug_refactor_inference" \
                    --log_dir="/home/hoopersm/refactor_debug/logs" \
                    --data_dir="/home/hoopersm/preprocessed_data/tissue" \
                    --split_csv_path="/home/hoopersm/archive/baseline_backbones/samplers/simple_tissue_splits_seed_1.csv" \
                    --height=256 \
                    --width=256 \
                    --time=1 \
                    --no_in_channel=3 \
                    --no_out_channel=2 \
                    --affine_aug=True \
                    --brightness_aug=True \
                    --gaussian_blur_aug=True \
                    --pre_model=Identity \
                    --backbone_model=omnivore \
                    --omnivore.size='tiny' \
                    --post_model=UperNet2D \
                    --task_type=seg \
                    --optim_type=adam \
                    --scheduler_type=None \
                    --loss_type=CrossEntropy \
                    --device=cuda \
                    --num_workers=4 \
                    --num_epochs=2 \
                    --batch_size=2 \
                    --optim.lr=0.0001 \
                    --optim.beta1=0.9 \
                    --optim.beta2=0.99 \
                    --ddp \
                    --override \ 
                     