export CUDA_VISIBLE_DEVICES=6,7

torchrun --standalone \
        --nnodes=1 \
        --nproc_per_node=2 \
        --max_restarts=0 \
        --master_port=9050 \
        --rdzv_id=100 \
        --rdzv_backend="c10d" \
        ../../run.py \
                --run_name="ptx_refactor_ddp" \
                --log_dir="/home/hoopersm/refactor_v1_FMImaging/projects/ptx_classify/logs" \
                --data_dir="/home/hoopersm/preprocessed_data/ptx" \
                --split_csv_path="/home/hoopersm/baseline_backbones/samplers/simple_ptx_splits_seed_1.csv" \
                --height=512 \
                --width=512 \
                --time=1 \
                --no_in_channel=1 \
                --no_out_channel=2 \
                --affine_aug=True \
                --brightness_aug=True \
                --gaussian_blur_aug=True \
                --pre_model=Identity \
                --backbone_model=omnivore_tiny \
                --post_model=NormPoolLinear \
                --task_type=class \
                --optim_type=adam \
                --scheduler_type=None \
                --loss_type=CrossEntropy \
                --device=cuda \
                --num_workers=0 \
                --num_epochs=50 \
                --batch_size=4 \
                --optim.lr=0.00001 \
                --optim.beta1=0.9 \
                --optim.beta2=0.99 \
                --exact_metrics=True \
                --override \
                --ddp
