export CUDA_VISIBLE_DEVICES=0

python ../../run.py --run_name="ptx_refactor1.5" \
                    --tasks="ptx_classify" \
                    --log_dir="/home/hoopersm/refactor_v1.5/logs" \
                    --data_dir="/home/hoopersm/preprocessed_data/ptx" \
                    --split_csv_path="/home/hoopersm/archive/baseline_backbones/samplers/simple_ptx_splits_seed_1.csv" \
                    --height=224 \
                    --width=224 \
                    --time=1 \
                    --no_in_channel=1 \
                    --no_out_channel=2 \
                    --affine_aug=True \
                    --brightness_aug=True \
                    --gaussian_blur_aug=True \
                    --pre_component=Identity \
                    --backbone_component=omnivore \
                    --omnivore.size='tiny' \
                    --post_component=NormPoolLinear \
                    --task_type=class \
                    --optim_type=adam \
                    --scheduler_type=None \
                    --loss_func=CrossEntropy \
                    --device=cuda \
                    --num_workers=4 \
                    --num_epochs=10 \
                    --batch_size=16 \
                    --optim.lr=0.00001 \
                    --optim.beta1=0.9 \
                    --optim.beta2=0.99 \
                    --exact_metrics=True \
                    --override \
                    --debug \
                    --save_model_components=True \
                    --checkpoint_frequency=3
